apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-go-basic-ygmk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-go-basic-ygmk
    app.kubernetes.io/part-of: appstudio
  name: devfile-sample-go-basic-ygmk
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: devfile-sample-go-basic-ygmk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: devfile-sample-go-basic-ygmk
    spec:
      containers:
      - image: quay.io/qijing/rhtap-push-goms-tenant/appstudio/devfile-sample-go-basic-ygmk@sha256:95c4c2246b79da919673c5859a6c5c6c6e4fe1e62254c35f5e42beb121638628
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
